### PR TITLE
fix(wc): sequential palette is inverted in dark theme

### LINKED ISSUE #797: [pie chart] sequential palette is inverted in dark theme
**Describe the bug**
Sequential palette in dark mode is displayed from lightest for bigger value to darkest for smaller value. It should be the opposite.

**To Reproduce**

1. Go to https://master--62216556f4e751003a75d602.chromatic.com/?path=/story/data-display-charts-pie-chart--default&args=data[0]:55;data[1]:44;data[2]:43;data[3]:22;data[4]:13;color:sequential-1
2. Apply dark mode
3. See the inverted colors

**Expected behavior**
Sequential palette should be used with darkest color = biggest value, lightest color = smallest value.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by code2nguyen**
- close  #797

### CODE REVIEW

**Comment by bcldvd** [comment]
Would it be feasible to always take first and last color value, and assign the rest as needed ?

**Comment by code2nguyen** [comment]
could you give an example about this idea, pls

**Comment by bcldvd** [comment]
See here:
image

Versus here:
image

The idea is to have the lowest value being always the lighter color, and the highest value the darkest color.
In between those two, colors would be assigned dependent on a number of data to display.

**Comment by code2nguyen** [comment]
I dont know, please create a feature request then ask more collaborate pls

**Review by bcldvd — APPROVED** [review]

**Review by dorsaffrigui — APPROVED** [review]

**Pull request merged**
